TARGET_COL = "PAY_AMT_SUM"
ID_COL = "PLAYERID"
PRED_PAYER_COL = "pred_is_payer" 
STAGE1_PROBA_COL = "stage1_proba"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu" 
#DEVICE = "cpu"

CAT_TASK_PARAMS = {"task_type": "GPU"} if DEVICE == "cuda" else {}
#CAT_TASK_PARAMS = {"task_type": "CPU"}

SEED = 2025
OPTUNA_SEED = 2025 
DEFAULT_SEEDS_STR = "2021,2022,2023,2024,2025,2026,2027,2028,2029,2030" 
N_JOBS = 12

PROJECT_ROOT = Path(__file__).resolve().parent       
DATA_DIR = PROJECT_ROOT.parent / "Data"              
DEFAULT_INPUT_DATA_PATH = DATA_DIR / "stage1_data.parquet"
DEF_OUTPUT_DIR = PROJECT_ROOT / "stage2_results"

DEFAULT_TRIALS = 30
DEFAULT_TEST_SIZE = 0.2 
BASE_SPLIT_SEED = 2025 

F_BETA = 2.0
MIN_PREC_AT_CUT = 0.55
CUT_STEP = 0.01
DELTA_AROUND = 0.3 
REWEIGHT_BY_FBETA = True

DEFAULT_WHALE_PCT = 0.05
WHALE_Q = 1.0 - DEFAULT_WHALE_PCT 
WHALE_CUT = 0.0

USE_STAGE1_FEATURES = False
EXCLUDE_PROBA_FEATURES = True
NO_CATBOOST = False
NO_LGBM = False
NO_TABPFN = False 

TABPFN_DEVICE = "auto"
TABPFN_CONFIGS = 32

ENSEMBLE_MODE = "weighted_by_ap"
SKIP_IF_EXISTS = False
